CREATE TABLE ANIME(
    ANIMEUNKID VARCHAR(255) NOT NULL,
    ANIME_NAME VARCHAR(255),
    THUMB_IMAGE_LINK TEXT(500),
    DSCRIPTION TEXT(2000),
    CURRENT_STATUS VARCHAR(100),
    RELEASE_YEAR INT,
    GENRE VARCHAR(255),
    LATEST_EPISODE VARCHAR(255),
    LATEST_RELEASE_DATE DATETIME,
    VIDEO_BOX_LINK TEXT(500),
    PRIMARY KEY (ANIMEUNKID)
)