CREATE TABLE EPISODES(
    ANIMEUNKID VARCHAR(255) NOT NULL,
    EPISODEUNKID VARCHAR(255) NOT NULL,
    EPISODE_NUMBER DOUBLE,
    EPISODE_TITLE VARCHAR(255),
    IS_VIDEO TEXT(500),
    VIDEO_DATA TEXT(2000),
    RELEASED_ON INT,
    EPISODE_URL TEXT(500),
    PRIMARY KEY (EPISODEUNKID),
    FOREIGN KEY (ANIMEUNKID) REFERENCES ANIME(ANIMEUNKID)
)