# Generated by Django 3.2.5 on 2021-08-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='epsiodes',
            new_name='episodes',
        ),
    ]
