# Generated by Django 3.2.5 on 2021-08-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeApp', '0002_rename_epsiodes_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='ANIMEUNKID',
            field=models.BigAutoField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
