# Generated by Django 3.2.6 on 2021-08-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeApp', '0003_alter_anime_animeunkid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='ANIMEUNKID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
