# Generated by Django 3.2.6 on 2021-08-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeApp', '0004_alter_anime_animeunkid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodes',
            old_name='EPSIODEUNKID',
            new_name='EPISODEUNKID',
        ),
        migrations.RenameField(
            model_name='episodes',
            old_name='EPISODE_URL',
            new_name='EPISODE_VIDEO_BOX_LINK',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='VIDEO_BOX_LINK',
        ),
    ]
